# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# enable true colors for gnome terminals
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",*256col*:Tc" # before tmux 3.2
# set -as terminal-features ",*256col*:RGB" # tmux 3.2 and after

# don't rename windows automatically
set-option -g allow-rename off

# Search Mode VI
set-window-option -g mode-keys vi

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# tmux-yank setting
set -g @yank_selection 'primary'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'dracula/tmux'

set -g @dracula-plugins "battery time"
set -g @dracula-day-month true
# Refresh status line every 5 seconds - Good for when music is playing / update time etc
set -g status-interval 5

# Start window and pane indices at 1.
set -g base-index 1
set -g pane-base-index 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
